name: Autoupdate pre-commit configs

on:
  # every sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  # on demand
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: write #require this to write to repo
  pull-requests: write #require this to create PR

jobs:
  auto-update:
    runs-on:
      - ubuntu-latest
    steps:
      - uses: SPHTech-Platform/gha-pre-commit-autoupdate@63fd59b2635b958b4128ba1f3b6859984b04ff47 # v1.1.1
        name: Update pre-commit config automatically
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
